# Generated by Django 5.2.10 on 2026-01-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("recipe_id", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("image", models.TextField()),
                ("cook_time", models.CharField(blank=True, max_length=100, null=True)),
                ("servings", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "favorites",
                "ordering": ["-created_at"],
            },
        ),
    ]
